apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: components
  namespace: argocd
spec:
  goTemplate: true

  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - primary
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - secondary
        - matchExpressions:
            - key: phase
              operator: NotIn
              values:
                - primary
                - secondary

  # Use generator to detect all helm charts
  generators:
    # Look for components in the charts directory
    - git:
        repoURL: git@github.com:m13t/devex-demo.git
        revision: HEAD
        files:
          - path: components/**/config.yaml

  # Begin the ArgoCD Application template
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
      namespace: argocd
      labels:
        phase: '{{default "tertiary" .sync.phase}}'

      # Cleanup removed applications from the cluster
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: infra
      sources:
        # First repository is the helm chart itself
        - repoURL: '{{.helm.repo}}'
          targetRevision: '{{.helm.revision}}'
          chart: '{{.helm.chart}}'
          helm:
            releaseName: '{{default .path.basenameNormalized .helm.releaseName}}'
            valueFiles:
              - '$values/components/{{.path.basename}}/values.yaml'
            ignoreMissingValueFiles: true

        # Third directory is for per-environment overrides and also acts
        # as the reference for the helm values
        - repoURL: git@github.com:m13t/devex-demo.git
          path: 'components/{{.path.basename}}'
          targetRevision: HEAD
          ref: values

      # Local cluster
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.helm.namespace}}'

      syncPolicy:
        # Self heal and prune resources
        automated:
          selfHeal: true
          prune: true

        # Use server-side apply for better efficiency and interop
        # between controllers making partial changes to manifests.
        # Also enable apply out of sync only rather than trying to
        # apply all resources in the application.
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - ApplyOutOfSyncOnly=true
