apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  goTemplate: true

  # Use generator to detect all helm charts
  generators:
    # Look for components in the charts directory
    - git:
        repoURL: git@github.com:m13t/devex-demo.git
        revision: HEAD
        directories:
          - path: platform/*

  # Begin the ArgoCD Application template
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
      namespace: argocd

      # Cleanup removed applications from the cluster
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: platform
      sources:
        # First repository is the helm chart itself
        - repoURL: git@github.com:m13t/devex-demo.git
          targetRevision: HEAD
          path: 'platform/{{.path.basename}}'

      # Local cluster
      destination:
        server: https://kubernetes.default.svc

      syncPolicy:
        # Self heal and prune resources
        automated:
          selfHeal: true
          prune: true

        # Use server-side apply for better efficiency and interop
        # between controllers making partial changes to manifests.
        # Also enable apply out of sync only rather than trying to
        # apply all resources in the application.
        syncOptions:
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
