configs:
  params:
    # Disavble TLS, will be handled by ingress
    server.insecure: true

    # Enable progressive syncs on application sets
    applicationsetcontroller.enable.progressive.syncs: true

  secret:
    argocdServerAdminPassword: '$2a$10$LaB2o7zCKpdX406bhC40NuxAvJijXm7Xh0UCDNepPdkXrOStJttpm'
    argocdServerAdminPasswordMtime: '2024-10-24T13:39:24BST'

  cm:
    # Track with annotations
    application.resourceTrackingMethod: annotation

    resource.customizations.ignoreDifferences.all: |
      managedFieldsManagers:
        - pilot-discovery

    resource.customizations: |
      networking.k8s.io/Ingress:
        health.lua: |
          hs = {}
          if obj.status ~= nil then
            hs.status = "Healthy"
          end
          return hs
